import { DocLayout } from "@/components/doc-layout"
import { DocContent } from "@/components/doc-content"
import { Smartphone, Network, Users, Zap, Shield } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

const validatorsSections = [
  { title: "Overview", href: "#overview" },
  { title: "What are Qubes?", href: "#what-are-qubes" },
  { title: "Role of Validators", href: "#role-of-validators" },
  { title: "Delegated Proof of Stake (DPoS)", href: "#dpos" },
  { title: "Becoming a Validator", href: "#becoming-validator" },
  { title: "Validator Rewards & Slashing", href: "#rewards-slashing" },
]

export default function ValidatorsPage() {
  return (
    <DocLayout title="Qubes & Validators" sections={validatorsSections}>
      <DocContent>
        <h1>Qubes & Validators</h1>

        <p className="text-xl text-gray-400 mb-12">
          Qubes are lightweight mobile nodes that act as validators in the Cubiq Network, enabling unprecedented
          decentralization and mobile participation.
        </p>

        <div className="bg-gradient-to-r from-blue-500/10 to-purple-500/10 border border-blue-500/20 rounded-lg p-8 mb-16">
          <h3 className="text-white font-semibold mb-6">Democratizing Consensus</h3>
          <p className="text-gray-300">
            Cubiq allows everyday mobile devices to contribute to network security and consensus, fostering a truly
            decentralized ecosystem.
          </p>
        </div>

        <div className="border-t border-gray-800 pt-12 mb-12">
          <h2 id="overview" className="mb-6">
            Overview
          </h2>

          <p className="mb-8">
            In traditional blockchain networks, running a full node or participating in validation often requires
            significant computational resources, limiting participation to a few powerful entities. Cubiq Network
            overcomes this by introducing "Qubes" – lightweight mobile nodes that can act as validators.
          </p>
          <p className="mb-8">
            This innovative approach, powered by zero-knowledge proofs, allows billions of mobile devices to participate
            in securing and decentralizing the network, making Cubiq truly mobile-native.
          </p>
        </div>

        <div className="border-t border-gray-800 pt-12 mb-12">
          <h2 id="what-are-qubes" className="mb-6">
            What are Qubes?
          </h2>

          <p className="mb-8">
            A Qube is a Cubiq mobile application instance running on a user's smartphone (Android or iOS) that performs
            critical validation tasks for the network. Unlike traditional full nodes, Qubes do not store the entire
            blockchain history or re-execute every transaction. Instead, they:
          </p>

          <ul className="mb-8 space-y-2">
            <li>
              <strong>Verify Zero-Knowledge Proofs:</strong> Qubes download compact zero-knowledge proofs (ZKPs)
              generated by Cloud Provers and cryptographically verify them using optimized WASM verifiers. This ensures
              the integrity of transactions and state transitions with minimal computational overhead.
            </li>
            <li>
              <strong>Participate in Consensus:</strong> Qubes that have staked QUBE tokens can participate in the
              Delegated Proof of Stake (DPoS) consensus mechanism, voting on the validity of new blocks.
            </li>
            <li>
              <strong>Propagate Blocks:</strong> They participate in a gossip-based peer-to-peer network to efficiently
              propagate new blocks and transaction information.
            </li>
          </ul>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
            <Card className="bg-gray-900/50 border-gray-800">
              <CardHeader className="flex flex-row items-center gap-4">
                <Smartphone className="w-8 h-8 text-blue-400" />
                <CardTitle className="text-white">Lightweight & Efficient</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-400">Minimal impact on mobile device resources (CPU, RAM, battery, data).</p>
              </CardContent>
            </Card>
            <Card className="bg-gray-900/50 border-gray-800">
              <CardHeader className="flex flex-row items-center gap-4">
                <Network className="w-8 h-8 text-purple-400" />
                <CardTitle className="text-white">True Decentralization</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-400">Enables broad participation in network security and governance.</p>
              </CardContent>
            </Card>
          </div>
        </div>

        <div className="border-t border-gray-800 pt-12 mb-12">
          <h2 id="role-of-validators" className="mb-6">
            Role of Validators
          </h2>

          <p className="mb-8">
            Validators (Qubes with staked tokens) play a crucial role in maintaining the security and integrity of the
            Cubiq Network. Their responsibilities include:
          </p>

          <ul className="mb-8 space-y-2">
            <li>
              <strong>Block Proposal:</strong> A selected validator proposes a new block containing a batch of
              transactions and their corresponding zero-knowledge proof.
            </li>
            <li>
              <strong>Proof Verification:</strong> All active validators verify the ZKP associated with the proposed
              block to ensure the validity of the transactions.
            </li>
            <li>
              <strong>Consensus Voting:</strong> Validators vote on the proposed block. Once a supermajority (2/3+) of
              the staked QUBE tokens vote in favor, the block is finalized.
            </li>
            <li>
              <strong>Network Participation:</strong> Maintaining an active Qube client and participating in the
              peer-to-peer network.
            </li>
          </ul>
        </div>

        <div className="border-t border-gray-800 pt-12 mb-12">
          <h2 id="dpos" className="mb-6">
            Delegated Proof of Stake (DPoS)
          </h2>

          <p className="mb-8">
            Cubiq Network utilizes a lightweight Delegated Proof of Stake (DPoS) consensus mechanism, optimized for
            mobile participation.
          </p>

          <h3 className="mt-8 mb-4">How DPoS Works in Cubiq</h3>
          <ul className="mb-8 space-y-2">
            <li>
              <strong>Delegation:</strong> QUBE token holders can "delegate" their stake to a validator (Qube) of their
              choice. This allows smaller token holders to participate in consensus without running a Qube themselves.
            </li>
            <li>
              <strong>Validator Selection:</strong> A set of active validators are chosen based on their total delegated
              stake. These validators are responsible for proposing and validating blocks.
            </li>
            <li>
              <strong>Voting:</strong> Active validators vote on proposed blocks. The weight of their vote is
              proportional to their total staked and delegated QUBE.
            </li>
            <li>
              <strong>Block Finality:</strong> Blocks achieve instant finality once a 2/3+ supermajority of staked
              tokens (via their delegated validators) confirm its validity.
            </li>
          </ul>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
            <Card className="bg-gray-900/50 border-gray-800">
              <CardHeader className="flex flex-row items-center gap-4">
                <Users className="w-8 h-8 text-green-400" />
                <CardTitle className="text-white">Community Governance</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-400">
                  DPoS empowers the community to choose validators and influence network direction.
                </p>
              </CardContent>
            </Card>
            <Card className="bg-gray-900/50 border-gray-800">
              <CardHeader className="flex flex-row items-center gap-4">
                <Zap className="w-8 h-8 text-yellow-400" />
                <CardTitle className="text-white">Efficient Consensus</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-400">Achieves high transaction throughput and fast block finality.</p>
              </CardContent>
            </Card>
          </div>
        </div>

        <div className="border-t border-gray-800 pt-12 mb-12">
          <h2 id="becoming-validator" className="mb-6">
            Becoming a Validator
          </h2>

          <p className="mb-8">To become an active validator (Qube) on the Cubiq Network, you will need to:</p>

          <ul className="mb-8 space-y-2">
            <li>
              <strong>Run the Cubiq App:</strong> Install and keep the Cubiq mobile application running on your device.
            </li>
            <li>
              <strong>Meet Minimum Stake:</strong> Hold and stake a minimum amount of QUBE tokens (details on minimum
              stake will be announced).
            </li>
            <li>
              <strong>Maintain Uptime:</strong> Ensure your Qube is consistently online and connected to the network to
              participate in block validation.
            </li>
            <li>
              <strong>Network Requirements:</strong> Your device will need a stable internet connection.
            </li>
          </ul>

          <h3 className="mt-8 mb-4">Validator Onboarding Process</h3>
          <p className="mb-8">
            A detailed guide for onboarding as a validator, including technical setup and best practices, will be
            provided closer to mainnet launch.
          </p>

          <Badge variant="outline" className="border-blue-500 text-blue-400">
            Validator Program Coming Soon
          </Badge>
        </div>

        <div className="border-t border-gray-800 pt-12">
          <h2 id="rewards-slashing" className="mb-6">
            Validator Rewards & Slashing
          </h2>

          <p className="mb-8">
            Validators are incentivized to act honestly and maintain network security through a system of rewards and
            penalties.
          </p>

          <h3 className="mt-8 mb-4">Rewards</h3>
          <ul className="mb-8 space-y-2">
            <li>
              <strong>Block Rewards:</strong> Validators who successfully propose and validate blocks receive a portion
              of newly minted QUBE tokens.
            </li>
            <li>
              <strong>Transaction Fees:</strong> Validators may also earn a share of transaction fees from the blocks
              they process.
            </li>
            <li>
              <strong>Delegator Share:</strong> Validators share a portion of their earned rewards with their
              delegators, encouraging more stake.
            </li>
          </ul>

          <h3 className="mt-8 mb-4">Slashing</h3>
          <p className="mb-8">
            To deter malicious behavior, validators can be "slashed," meaning a portion of their staked QUBE tokens are
            forfeited, for actions such as:
          </p>
          <ul className="mb-8 space-y-2">
            <li>Double-signing blocks.</li>
            <li>Downtime or prolonged inactivity.</li>
            <li>Maliciously attempting to fork the chain.</li>
          </ul>

          <Card className="bg-gray-900/50 border-gray-800 mb-8">
            <CardHeader className="flex flex-row items-center gap-4">
              <Shield className="w-8 h-8 text-red-400" />
              <CardTitle className="text-white">Network Security</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-400">
                The reward and slashing mechanisms ensure validators are aligned with the network's best interests.
              </p>
            </CardContent>
          </Card>
        </div>
      </DocContent>
    </DocLayout>
  )
}
